//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTRIKSService.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eTRIKS_schemaEntitiesNew : DbContext
    {
        public eTRIKS_schemaEntitiesNew()
            : base("name=eTRIKS_schemaEntitiesNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Activity_TAB> Activity_TAB { get; set; }
        public DbSet<CVterm_TAB> CVterm_TAB { get; set; }
        public DbSet<Db_TAB> Db_TAB { get; set; }
        public DbSet<DBxref_TAB> DBxref_TAB { get; set; }
        public DbSet<Derived_Variable_Method_TAB> Derived_Variable_Method_TAB { get; set; }
        public DbSet<Dictionary_TAB> Dictionary_TAB { get; set; }
        public DbSet<Study_TAB> Study_TAB { get; set; }
        public DbSet<Variable_Def_TAB> Variable_Def_TAB { get; set; }
        public DbSet<Variable_Ref_TAB> Variable_Ref_TAB { get; set; }
    }
}
