FROM microsoft/aspnetcore-build:1.1-projectjson

RUN apt-get update && \
    apt-get install -y --no-install-recommends mysql-client && \
    apt-get purge -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /sln
COPY . .
ENTRYPOINT ["./db-init.sh"]

