version: '3.4'

services:
  ptm-server:
    image: iemam/platformtm-server:unicorn1.2
    build:
      context: PlatformTM-server
      dockerfile: PlatformTM.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    volumes:
      - "ptmappdata:/app_data"
    ports:
      - "80:80"
volumes:
  ptmappdata: