//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DomainVariable
{
	public virtual string OID
	{
		get;
		set;
	}

	public virtual string domainName
	{
		get;
		set;
	}

	public virtual string description
	{
		get;
		set;
	}

	public virtual string dataType
	{
		get;
		set;
	}

}

