-- MySQL Script generated by MySQL Workbench
-- 08/15/14 11:43:24
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ISATemplate_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ISATemplate_schema` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema eTRIKS_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eTRIKS_schema` DEFAULT CHARACTER SET latin1 ;
USE `ISATemplate_schema` ;

-- -----------------------------------------------------
-- Table `ISATemplate_schema`.`Domain_Dataset_Template_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISATemplate_schema`.`Domain_Dataset_Template_TAB` (
  `OID` VARCHAR(200) NOT NULL,
  `domainName` VARCHAR(2000) NULL DEFAULT NULL,
  `class` VARCHAR(200) NULL DEFAULT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  `structure` VARCHAR(200) NULL DEFAULT NULL,
  `repeating` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`OID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ISATemplate_schema`.`Domain_Variable_Template_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISATemplate_schema`.`Domain_Variable_Template_TAB` (
  `OID` VARCHAR(200) NOT NULL,
  `name` VARCHAR(2000) NULL DEFAULT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  `dataType` VARCHAR(200) NULL DEFAULT NULL,
  `datasetId` VARCHAR(200) NULL DEFAULT NULL,
  `variableType` VARCHAR(200) NULL DEFAULT NULL,
  `role` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`OID`),
  INDEX `datasetId_idx` (`datasetId` ASC),
  INDEX `dictionary_idx` (`variableType` ASC),
  CONSTRAINT `datasetId`
    FOREIGN KEY (`datasetId`)
    REFERENCES `ISATemplate_schema`.`Domain_Dataset_Template_TAB` (`OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `eTRIKS_schema` ;

-- -----------------------------------------------------
-- Table `eTRIKS_schema`.`Study_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eTRIKS_schema`.`Study_TAB` (
  `OID` VARCHAR(200) NOT NULL,
  `name` VARCHAR(2000) NULL DEFAULT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`OID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eTRIKS_schema`.`Activity_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eTRIKS_schema`.`Activity_TAB` (
  `OID` VARCHAR(200) NOT NULL,
  `name` VARCHAR(2000) NULL DEFAULT NULL,
  `studyId` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`OID`),
  INDEX `studyId_idx` (`studyId` ASC),
  CONSTRAINT `study`
    FOREIGN KEY (`studyId`)
    REFERENCES `eTRIKS_schema`.`Study_TAB` (`OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eTRIKS_schema`.`Db_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eTRIKS_schema`.`Db_TAB` (
  `OID` VARCHAR(200) NOT NULL,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `urlPrefix` VARCHAR(2000) NULL DEFAULT NULL,
  `url` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`OID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eTRIKS_schema`.`DBxref_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eTRIKS_schema`.`DBxref_TAB` (
  `OID` VARCHAR(200) NOT NULL,
  `accession` VARCHAR(200) NULL DEFAULT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  `db` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`OID`),
  INDEX `database_idx` (`db` ASC),
  CONSTRAINT `database`
    FOREIGN KEY (`db`)
    REFERENCES `eTRIKS_schema`.`Db_TAB` (`OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eTRIKS_schema`.`Dictionary_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eTRIKS_schema`.`Dictionary_TAB` (
  `OID` VARCHAR(200) NOT NULL,
  `name` VARCHAR(2000) NULL DEFAULT NULL,
  `version` VARCHAR(200) NULL DEFAULT NULL,
  `url` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`OID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eTRIKS_schema`.`CVterm_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eTRIKS_schema`.`CVterm_TAB` (
  `abbrv` VARCHAR(200) NOT NULL,
  `name` VARCHAR(2000) NULL DEFAULT NULL,
  `order` INT(11) NULL DEFAULT NULL,
  `rank` INT(11) NULL DEFAULT NULL,
  `userSpecified` BIT(1) NULL DEFAULT NULL,
  `dictionartyId` VARCHAR(200) NULL DEFAULT NULL,
  `dbref` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`abbrv`),
  INDEX `dictionary_idx` (`dictionartyId` ASC),
  INDEX `dbref_idx` (`dbref` ASC),
  CONSTRAINT `dbref`
    FOREIGN KEY (`dbref`)
    REFERENCES `eTRIKS_schema`.`DBxref_TAB` (`OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dictionary`
    FOREIGN KEY (`dictionartyId`)
    REFERENCES `eTRIKS_schema`.`Dictionary_TAB` (`OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eTRIKS_schema`.`Variable_Def_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eTRIKS_schema`.`Variable_Def_TAB` (
  `datasetId` VARCHAR(200) NULL DEFAULT NULL,
  `variableId` VARCHAR(200) NOT NULL,
  `name` VARCHAR(2000) NULL DEFAULT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  `dataType` VARCHAR(200) NULL DEFAULT NULL,
  `studyId` VARCHAR(200) NULL,
  `isCurated` BIT(1) NULL DEFAULT NULL,
  `variableType` VARCHAR(200) NULL,
  `role` VARCHAR(200) NULL,
  PRIMARY KEY (`variableId`),
  INDEX `variableType_dictionary_fK_idx` (`variableType` ASC),
  CONSTRAINT `variableType_dictionary_fK`
    FOREIGN KEY (`variableType`)
    REFERENCES `eTRIKS_schema`.`Dictionary_TAB` (`OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eTRIKS_schema`.`Derived_Variable_Map_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eTRIKS_schema`.`Derived_Variable_Map_TAB` (
  `variableId` VARCHAR(200) NOT NULL,
  `sourceVariableId` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`variableId`, `sourceVariableId`),
  INDEX `derived_idx` (`sourceVariableId` ASC),
  CONSTRAINT `variable_FK`
    FOREIGN KEY (`sourceVariableId`)
    REFERENCES `eTRIKS_schema`.`Variable_Def_TAB` (`variableId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `variable`
    FOREIGN KEY (`variableId`)
    REFERENCES `eTRIKS_schema`.`Variable_Def_TAB` (`variableId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eTRIKS_schema`.`Derived_Variable_Method_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eTRIKS_schema`.`Derived_Variable_Method_TAB` (
  `derivedVariableId` VARCHAR(200) NOT NULL,
  `methodDescription` VARCHAR(2000) NULL DEFAULT NULL,
  `type` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`derivedVariableId`),
  CONSTRAINT `FK_Variable`
    FOREIGN KEY (`derivedVariableId`)
    REFERENCES `eTRIKS_schema`.`Variable_Def_TAB` (`variableId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eTRIKS_schema`.`Variable_Ref_TAB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eTRIKS_schema`.`Variable_Ref_TAB` (
  `variableId` VARCHAR(200) NOT NULL,
  `activityId` VARCHAR(200) NOT NULL,
  `orderNo` INT(11) NULL DEFAULT NULL,
  `mandatory` BIT(1) NULL DEFAULT NULL,
  `keySequence` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`variableId`, `activityId`),
  INDEX `activity_idx` (`activityId` ASC),
  CONSTRAINT `activity`
    FOREIGN KEY (`activityId`)
    REFERENCES `eTRIKS_schema`.`Activity_TAB` (`OID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `variablefk`
    FOREIGN KEY (`variableId`)
    REFERENCES `eTRIKS_schema`.`Variable_Def_TAB` (`variableId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
