//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTRIKS.Commons.Persistence.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_TAB
    {
        public Activity_TAB()
        {
            this.Activity_Dataset_TAB = new HashSet<Activity_Dataset_TAB>();
        }
    
        public string OID { get; set; }
        public string name { get; set; }
        public string studyId { get; set; }
    
        public virtual ICollection<Activity_Dataset_TAB> Activity_Dataset_TAB { get; set; }
        public virtual Study_TAB Study_TAB { get; set; }
    }
}
