//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTRIKS.Commons.Persistence.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVterm_TAB
    {
        public string abbrv { get; set; }
        public string name { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<bool> userSpecified { get; set; }
        public string dictionartyId { get; set; }
        public string dbref { get; set; }
    
        public virtual DBxref_TAB DBxref_TAB { get; set; }
        public virtual Dictionary_TAB Dictionary_TAB { get; set; }
    }
}
