//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTRIKS.Commons.Persistence.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_TAB
    {
        public Db_TAB()
        {
            this.DBxref_TAB = new HashSet<DBxref_TAB>();
        }
    
        public string OID { get; set; }
        public string name { get; set; }
        public string urlPrefix { get; set; }
        public string url { get; set; }
    
        public virtual ICollection<DBxref_TAB> DBxref_TAB { get; set; }
    }
}
