//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTRIKS.Commons.Persistence.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBxref_TAB
    {
        public DBxref_TAB()
        {
            this.CVterm_TAB = new HashSet<CVterm_TAB>();
        }
    
        public string OID { get; set; }
        public string accession { get; set; }
        public string description { get; set; }
        public string db { get; set; }
    
        public virtual ICollection<CVterm_TAB> CVterm_TAB { get; set; }
        public virtual Db_TAB Db_TAB { get; set; }
    }
}
