//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTRIKS.Commons.Persistence.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Derived_Variable_Map_TAB
    {
        public string variableId { get; set; }
        public string sourceVariableId { get; set; }
        public string temp { get; set; }
    
        public virtual Variable_Def_TAB Variable_Def_TAB { get; set; }
        public virtual Variable_Def_TAB Variable_Def_TAB1 { get; set; }
    }
}
