//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTRIKS.Commons.Persistence.ModelFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eTRIKSDataModel_Entities : DbContext
    {
        public eTRIKSDataModel_Entities()
            : base("name=eTRIKSDataModel_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity_Dataset_TAB> Activity_Dataset_TAB { get; set; }
        public virtual DbSet<Activity_TAB> Activity_TAB { get; set; }
        public virtual DbSet<CVterm_TAB> CVterm_TAB { get; set; }
        public virtual DbSet<Db_TAB> Db_TAB { get; set; }
        public virtual DbSet<DBxref_TAB> DBxref_TAB { get; set; }
        public virtual DbSet<Derived_Variable_Map_TAB> Derived_Variable_Map_TAB { get; set; }
        public virtual DbSet<Derived_Variable_Method_TAB> Derived_Variable_Method_TAB { get; set; }
        public virtual DbSet<Dictionary_TAB> Dictionary_TAB { get; set; }
        public virtual DbSet<Study_TAB> Study_TAB { get; set; }
        public virtual DbSet<Variable_Def_TAB> Variable_Def_TAB { get; set; }
        public virtual DbSet<Variable_Ref_TAB> Variable_Ref_TAB { get; set; }
    }
}
