using System.Collections.Generic;
using eTRIKS.Commons.Core.Domain.Model.Users.Datasets;

namespace eTRIKS.Commons.Service.DTOs
{

    /**
     * This DTO provides the expected JSON for jsTree library to build a tree
     * Required properties
     * Id //will be autogenerated if omitted
     * text //node text
     * isGroup // a flag to include children node or not
     * */
    public class TreeNodeDTO
    {
        public string Id { get; set; }
        public List<TreeNodeDTO> Children { get; set; }
        public string Text { get; set; }
        public DataFieldDTO Field { get; set; }
        public bool IsGroup { get; set; }
        public string Type { get; set; }
        public Dictionary<string,string> li_attr { get; set; }

        public TreeNodeDTO()
        {
            //li_attr = new List<string>();
            li_attr = new Dictionary<string, string>() {
                //{"class","btn btn-default btn-xs" },
                {"data-drag","true"},
                //{"data-jqyoui-options","{ revert: 'invalid'}"},
                {"jqyoui-draggable","{animate: true}"}
            };
        }
    }


    //public class Field
    //{
    //    public string FieldName { get; set; } //INJECTION SITE PAIN // BMI // STUDY
    //    public int FieldNameId { get; set; }
    //    public string FieldVariable { get; set; } //AEDECOD // VSTESTCD // STUDYID
    //    public string ValuesVariable { get; set; } //AESEV // VSORRES (what will be added as a projection field) // STUDYID
    //    public ValueSetDTO Filters { get; set; }
    //    private string _displayName;
    //    public string DisplayName
    //    {
    //        get { return Domain + " - " + (GroupName != null ? (GroupName + " - ") : "") + FieldName + " [" + ValuesVariable + "]"; }
    //        set { _displayName = value; }
    //    }
    //    public string Id { get; set; }
    //    public string DomainCode { get; set; }
    //    public string GroupName { get; set; }
    //    public string GroupVarName { get; set; }
    //    public string Domain { get; set; }
    //}


}
